name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Runs the workflow when a new version tag is created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools==58.1.0 numpy==1.23.5 Cython==3.0.10 scikit-learn==1.5.1 wheel==0.45.1 build==1.2.2 twine==6.1.0

    - name: Build package
      run: |
        python -m build

    - name: Check package (optional)
      run: |
        twine check dist/*

    - name: Publish to PyPI
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'  # Publish only once
      env:
        TWINE_USERNAME: __TOKEN__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
